services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    container_name: venture-launch-frontend
    networks:
      - venture-launch-network
    env_file: ./.env.dev
    ports:
      - ${INTERNAL_FRONTEND_PORT}:3000
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    container_name: venture-launch-backend
    networks:
      - venture-launch-network
    env_file: ./.env.dev
    ports:
      - ${INTERNAL_BACKEND_PORT}:8000
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: venture-launch-database
    networks:
      - venture-launch-network
    env_file: ./.env.dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - ${INTERNAL_DATABASE_PORT}:5432
    expose:
      - ${INTERNAL_DATABASE_PORT}
    volumes:
      - database_data:/var/lib/postgresql/data
    restart: on-failure

  rabbitmq:
    image: rabbitmq:3-management
    container_name: venture-launch-rabbitmq
    networks:
      - venture-launch-network
    env_file:
      - ./.env.dev
    ports:
      - ${INTERNAL_RABBITMQ_PORT_A}:5672
      - ${INTERNAL_RABBITMQ_PORT_B}:15672
    expose:
      - ${INTERNAL_RABBITMQ_PORT_A}
      - ${INTERNAL_RABBITMQ_PORT_B}

  rust:
    build:
      context: ./venture-launch-dao
      dockerfile: ./.Dockerfile.dev
    container_name: venture-launch-rust
    networks:
      - venture-launch-network
    env_file: ./venture-launch-dao/.env
    volumes:
      - ./venture-launch-dao/src:/app/src
    depends_on:
      - rabbitmq
      - backend
    restart: on-failure

networks:
  venture-launch-network:
    driver: bridge

volumes:
  database_data:
